name = "test"
version = "0.1.0"
defaultTargets = ["test"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0-rc1"

[[lean_lib]]
name = "type_theory"

[[lean_lib]]
name = "tactic"

[[lean_exe]]
name = "test"
root = "Main"
